export const LOAD_MOST_POPULAR_USERS = 'LOAD_MOST_POPULAR_USERS'
export const ERROR_WHILE_FETCHING_INITIAL_TABLE = 'ERROR_WHILE_FETCHING_INITIAL_TABLE'
export const CITY_TO_SEARCH = 'CITY_TO_SEARCH'

