export const LOAD_MOST_POPULAR_USERS = 'LOAD_MOST_POPULAR_USERS'
export const ERROR_WHILE_FETCHING_INITIAL_TABLE =
  'ERROR_WHILE_FETCHING_INITIAL_TABLE'
export const CITY_TO_SEARCH = 'CITY_TO_SEARCH'
// export const UPDATE_TOP_TEN_USER_IN_CITY = 'UPDATE_TOP_TEN_USER_IN_CITY'
